version: 0.0
os: linux
files: 
  - source: /
    destination: /server/deploy-root/hbhan-tomcat/
    
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall
      timeout: 300
      runas: root